### PR TITLE
Teaches unit.rb to require spec_helper

### PR DESCRIPTION
**Pull request by RyanFrantz**
- More for #3

Signed-off-by: Ryan Frantz <ryanleefrantz@gmail.com>

### CODE REVIEW

**Review by rmcleod8 — APPROVED** [review]
lgtm

**Review by rmcleod8 — APPROVED** [review]
still lgtm

**Review by johnbellone — APPROVED** [review]
This looks good to me.

**Review by johnbellone — APPROVED** [review]
This looks good to me.

**Pull request merged**
